"""Command-line client for the Agent Hub daemon."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import socket
import sys
from typing import Any

from . import __version__


DEFAULT_CONFIG = """# Generated by `agent-hub init`.
# Keep this file local and set AGENT_HUB_CONFIG to its absolute path.

agentd:
  ipc:
    transport: tcp
    tcp_host: 127.0.0.1
    tcp_port: 19876

  cline:
    executable: auto
    timeout_seconds: 600
    stall_threshold_seconds: 300
    max_retries: 1
    mock: false
    mock_exit_code: 0
    mock_delay_seconds: 1.0
    kill_on_shutdown: false
    retention_days: 30
    max_task_history: 1000
    env: {}

  database:
    path: .agent-hub/state.sqlite

  logs:
    dir: .agent-hub/logs/

  safety:
    protected_paths: []
    forbidden_commands: []
    allow_network: false
    max_execution_time_seconds: 3600
"""


def rpc(
    method: str,
    params: dict[str, Any] | None = None,
    *,
    host: str = "127.0.0.1",
    port: int = 19876,
    timeout: float = 15,
) -> Any:
    """Send one JSON-Lines request and return the matching response result."""

    request_id = "cli"
    payload = {
        "type": "request",
        "id": request_id,
        "method": method,
        "params": params or {},
    }

    with socket.create_connection((host, port), timeout=timeout) as connection:
        connection.settimeout(timeout)
        connection.sendall((json.dumps(payload) + "\n").encode("utf-8"))
        buffer = b""

        while True:
            while b"\n" not in buffer:
                chunk = connection.recv(1 << 20)
                if not chunk:
                    raise RuntimeError("connection closed by daemon")
                buffer += chunk

            line, buffer = buffer.split(b"\n", 1)
            if not line.strip():
                continue

            message = json.loads(line.decode("utf-8"))
            if message.get("type") == "push":
                continue
            if message.get("type") != "response" or message.get("id") != request_id:
                continue
            if "error" in message:
                raise RuntimeError(str(message["error"]))
            return message.get("result")


def write_default_config(path: str, *, force: bool = False) -> Path:
    """Write a local configuration template and return its resolved path."""

    target = Path(path).expanduser().resolve()
    if target.exists() and not force:
        raise FileExistsError(
            f"{target} already exists; pass --force to replace it"
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(DEFAULT_CONFIG, encoding="utf-8")
    return target


def format_task(task: dict[str, Any]) -> str:
    """Format one task for human-readable status output."""

    return (
        f"{task['id']}  {task['state']:<16} "
        f"exit={task.get('cline_exit_code')} "
        f"retries={task.get('retry_count', 0)}/{task.get('max_retries', 1)} "
        f"created={task.get('created_at', '?')}\n"
        f"    {(task.get('prompt') or '')[:100]}"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="agent-hub",
        description="Control a local Agent Hub daemon.",
    )
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=19876)
    parser.add_argument("--json", action="store_true", help="print raw JSON")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="cmd", required=True)

    init_parser = sub.add_parser("init", help="write a local configuration template")
    init_parser.add_argument("--path", default="config.local.yaml")
    init_parser.add_argument("--force", action="store_true")

    sub.add_parser("ping")

    submit = sub.add_parser("submit")
    submit.add_argument("prompt")
    submit.add_argument("--cwd", default=os.getcwd())

    goal = sub.add_parser("goal", aliases=["start-goal"])
    goal.add_argument("objective")
    goal.add_argument("--cwd", default=os.getcwd())
    goal.add_argument("--max-iterations", type=int, default=None)
    goal.add_argument("--max-failures", type=int, default=None)
    goal.add_argument("--completion-criteria", default="")
    goal.add_argument("--stop-conditions", default="")
    goal.add_argument("--model-call-budget", type=int, default=None)

    sub.add_parser("status")

    cancel = sub.add_parser("cancel")
    cancel.add_argument("task_id")

    delete_goal = sub.add_parser("delete-goal")
    delete_goal.add_argument("goal_id")

    log = sub.add_parser("log")
    log.add_argument("task_id")
    log.add_argument("--lines", type=int, default=80)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.cmd == "init":
        try:
            path = write_default_config(args.path, force=args.force)
        except OSError as exc:
            print(f"agent-hub: error: {exc}", file=sys.stderr)
            return 1
        if args.json:
            print(json.dumps({"config_path": str(path)}, ensure_ascii=False))
        else:
            print(f"wrote: {path}")
            print(f'export AGENT_HUB_CONFIG="{path}"')
        return 0

    try:
        if args.cmd == "ping":
            result = rpc("ping", host=args.host, port=args.port)
        elif args.cmd == "submit":
            result = rpc(
                "submit_task",
                {"prompt": args.prompt, "cwd": args.cwd},
                host=args.host,
                port=args.port,
                timeout=30,
            )
        elif args.cmd in ("goal", "start-goal"):
            params: dict[str, Any] = {
                "objective": args.objective,
                "cwd": args.cwd,
            }
            if args.max_iterations is not None:
                params["max_iterations"] = args.max_iterations
            if args.max_failures is not None:
                params["max_failures"] = args.max_failures
            if args.completion_criteria:
                params["completion_criteria"] = args.completion_criteria
            if args.stop_conditions:
                params["stop_conditions"] = args.stop_conditions
            if args.model_call_budget is not None:
                params["model_call_budget"] = args.model_call_budget
            result = rpc(
                "start_goal",
                params,
                host=args.host,
                port=args.port,
                timeout=30,
            )
        elif args.cmd == "status":
            result = rpc("get_status", host=args.host, port=args.port)
        elif args.cmd == "cancel":
            result = rpc(
                "cancel_task",
                {"task_id": args.task_id},
                host=args.host,
                port=args.port,
            )
        elif args.cmd == "delete-goal":
            result = rpc(
                "delete_goal",
                {"goal_id": args.goal_id},
                host=args.host,
                port=args.port,
                timeout=30,
            )
        elif args.cmd == "log":
            result = rpc(
                "get_log_tail",
                {"task_id": args.task_id, "lines": args.lines},
                host=args.host,
                port=args.port,
            )
        else:
            parser.error("unknown command")
            return 2
    except (OSError, RuntimeError, ValueError, json.JSONDecodeError) as exc:
        print(f"agent-hub: error: {exc}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(result, ensure_ascii=False))
        return 0

    if args.cmd == "ping":
        print(f"OK: daemon responding (version {result.get('version', '?')})")
    elif args.cmd == "submit":
        print(f"submitted: {result['task_id']}  state={result['state']}")
    elif args.cmd in ("goal", "start-goal"):
        print(f"goal started: {result['id']}  state={result['state']}")
    elif args.cmd == "status":
        print(f"active={result['active_count']} total={result['total_count']}")
        for task in result.get("tasks", []):
            print(format_task(task))
    elif args.cmd == "cancel":
        print(f"cancelled: {result['task_id']}  state={result['state']}")
    elif args.cmd == "delete-goal":
        print(
            f"deleted: {result['goal_id']}  "
            f"tasks_removed={result['deleted_task_count']}"
        )
    elif args.cmd == "log":
        sys.stdout.write(result.get("stdout", ""))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
